version: '3'

services:
  app_test:
    container_name: full_app_test
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - api_test:/app/src/app
    depends_on:
      - postgres_test
    networks:
      - fullstack_test

  postgres_test:
    image: postgres:latest
    container_name: full_db_test_posgtres
    environment: 
      - POSTGRES_USER=${TestDbUser}
      - POSTGRES_PASSWORD=${TestDbPassword}
      - POSTGRES_DB=${TestDbName}
      - DATABASE_HOST=${TestDbHost}
    ports:
      - '5555:5432'
    volumes:
      - database_postgres_test:/var/lib/postgresql/data
    networks:
      - fullstack_test

volumes:
  api_test:
  database_postgres_test:

networks:
  fullstack_test:
    driver: bridge