apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: fullstack-postgres

spec:
  storageClassName: manual #storage class. a pv claim requesting the same storageclass can be bound to this
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:               #hostPath PersistentVolume is used for development and testing. It uses a file/directory on the Node to emulate network-attached storage
    path: "/mnt/data" 
  persistentVolumeReclaimPolicy: Retain #Retaint the PV even after PVC is deleted