apiVersion: v1
kind: PersistentVolumeClaim #PVC requests PV
metadata:
  name: postgres-pv-claim   #claim name and labels
  labels:
    app: fullstack-postgres
  
spec:                               # access mode and resource limits
  storageClassName: manual          # request a certain storage class
  accessModes:
    - ReadWriteMany # Readwritemany means the volume can be mounted as read-write by many nodes
  resources:
    requests:
      storage: 5Gi